name: Validate Domains PR

on:
  pull_request:
    paths:
      - "domains.txt"

permissions:
  contents: read
  pull-requests: write

jobs:

  validate:
    runs-on: ubuntu-latest

    env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Validate Domain format
        run: node scripts/validate-domains.js